using System;
using System.Collections.Generic;
using System.Text;
using TinyCSharp.Compiler.Parsing;

namespace TinyCSharp.Compiler.Generation;

public sealed class CSharpGenerator
{
    public string Generate(TinySyntaxTree syntaxTree)
    {
        var sb = new StringBuilder();
        
        // Add auto-generated header
        sb.AppendLine("// <auto-generated />");
        var sourceFileName = string.IsNullOrWhiteSpace(syntaxTree.SourceFilePath)
            ? "unknown.tcs"
            : Path.GetFileName(syntaxTree.SourceFilePath);
        sb.AppendLine("// This file is generated from " + sourceFileName + ".");
        sb.AppendLine("// Manual changes will be overwritten.");
        sb.AppendLine();
        
        // Add using directives
        var usingDirectives = new HashSet<string>(syntaxTree.Usings);
        
        // Add System for DateTime, Guid, etc.
        if (syntaxTree.Properties.Any(p => p.Type == "DateTime" || p.Type == "Guid"))
        {
            usingDirectives.Add("System");
        }
        
        // Sort using directives
        var sortedUsings = new List<string>(usingDirectives);
        sortedUsings.Sort();
        
        foreach (var @using in sortedUsings)
        {
            sb.AppendLine($"using {@using};");
        }
        
        // Add namespace declaration
        if (!string.IsNullOrEmpty(syntaxTree.Namespace))
        {
            sb.AppendLine($"namespace {syntaxTree.Namespace};");
            sb.AppendLine();
        }
        
        // Add class declaration
        sb.AppendLine($"public sealed class {syntaxTree.ClassName}");
        sb.AppendLine("{");
        
        // Add properties
        foreach (var property in syntaxTree.Properties)
        {
            var declaration = $"    public {property.Type} {property.Name} {{ get; {GetSetter(property.Mode)} }}";
            if (property.Type == "string" && property.Mode == 0)
            {
                declaration += " = string.Empty;";
            }

            sb.AppendLine(declaration);
        }
        
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    private string GetSetter(int mode)
    {
        switch (mode)
        {
            case 0:
                return "set;";
            case 1:
                return "init;";
            case 2:
                return "private set;";
            default:
                return "set;";
        }
    }
    
}
