using TinyCSharp.Compiler.Compilation;
using TinyCSharp.Compiler.Generation;
using TinyCSharp.Compiler.Parsing;
using Xunit;

namespace TinyCSharp.Compiler.Tests;

public sealed class CompilerTests
{
    [Fact]
    public void Parse_PscDeclaration_WithAliasesAndModes()
    {
        var parser = new TinyParser();
        var tree = parser.Parse("psc Match => Id,Name,Age:i,StartedAt:dt|1,Code:i|2");

        Assert.True(tree.IsValid);
        Assert.Equal("Match", tree.ClassName);
        Assert.Equal(5, tree.Properties.Count);
        Assert.Equal("string", tree.Properties[0].Type);
        Assert.Equal(0, tree.Properties[0].Mode);
        Assert.Equal("int", tree.Properties[2].Type);
        Assert.Equal("DateTime", tree.Properties[3].Type);
        Assert.Equal(1, tree.Properties[3].Mode);
        Assert.Equal(2, tree.Properties[4].Mode);
    }

    [Fact]
    public void Parse_ExplicitNamespace_AndUsings()
    {
        var parser = new TinyParser();
        var tree = parser.Parse("n:MyCompany.Domain\nu:System.Collections.Generic\nu:MyCompany.Contracts\npsc Match => Result:MatchResult");

        Assert.True(tree.IsValid);
        Assert.Equal("MyCompany.Domain", tree.Namespace);
        Assert.Equal(new[] { "System.Collections.Generic", "MyCompany.Contracts" }, tree.Usings);
        Assert.Equal("MatchResult", tree.Properties[0].Type);
    }

    [Fact]
    public void Generate_ProducesHeaderNamespaceAndProperties()
    {
        var tree = new TinySyntaxTree
        {
            SourceFilePath = "/tmp/Match.tcs",
            Namespace = "Tiny.Sample",
            ClassName = "Match",
            Properties =
            {
                new TinyProperty("Id", "string", 0),
                new TinyProperty("Number", "int", 1),
                new TinyProperty("Code", "int", 2)
            }
        };

        var generator = new CSharpGenerator();
        var output = generator.Generate(tree);

        Assert.Contains("// <auto-generated />", output);
        Assert.Contains("// This file is generated from Match.tcs.", output);
        Assert.Contains("namespace Tiny.Sample;", output);
        Assert.Contains("public sealed class Match", output);
        Assert.Contains("public string Id { get; set; } = string.Empty;", output);
        Assert.Contains("public int Number { get; init; }", output);
        Assert.Contains("public int Code { get; private set; }", output);
    }

    [Fact]
    public async Task CompileAsync_OverwritesSiblingCs_AndInfersNamespace()
    {
        var root = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);

        try
        {
            var projectPath = Path.Combine(root, "MyCompany.App.csproj");
            await File.WriteAllTextAsync(projectPath, "<Project><PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Tiny.Sample</RootNamespace></PropertyGroup></Project>");

            var folder = Path.Combine(root, "Domain", "Matches");
            Directory.CreateDirectory(folder);

            var tcsPath = Path.Combine(folder, "Match.tcs");
            var csPath = Path.Combine(folder, "Match.cs");

            await File.WriteAllTextAsync(tcsPath, "psc Match => Id,Name");
            await File.WriteAllTextAsync(csPath, "// manual file\nclass Old { }");

            var compiler = new TinyProjectCompiler();
            var result = await compiler.CompileAsync(projectPath);

            Assert.True(result.Success);
            var output = await File.ReadAllTextAsync(csPath);
            Assert.Contains("// <auto-generated />", output);
            Assert.Contains("namespace Tiny.Sample.Domain.Matches;", output);
            Assert.DoesNotContain("manual file", output);
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }
    }
}
