using TinyCSharp.Compiler.Compilation;
using TinyCSharp.Compiler.Generation;
using TinyCSharp.Compiler.Language;
using TinyCSharp.Compiler.Parsing;
using Xunit;

namespace TinyCSharp.Compiler.Tests;

public sealed class CompilerTests
{
    [Theory]
    [InlineData("pc", "public class")]
    [InlineData("psc", "public sealed class")]
    [InlineData("ic", "internal class")]
    [InlineData("isc", "internal sealed class")]
    public void Parse_CompactTypeDeclaration_IsCanonical(string token, string expectedDeclaration)
    {
        var parser = new TinyParser();
        var tree = parser.Parse($"{token} Match => Id");

        Assert.True(tree.IsValid);
        Assert.Equal(token, tree.TypeDeclaration.ToToken());

        var generator = new CSharpGenerator();
        var output = generator.Generate(tree);
        Assert.Contains($"{expectedDeclaration} Match", output);
    }

    [Fact]
    public void Parse_PscDeclaration_WithAliasesAndModes()
    {
        var parser = new TinyParser();
        var tree = parser.Parse("psc Match => Id,Name,Age:i,StartedAt:dt|1,Code:i|2");

        Assert.True(tree.IsValid);
        Assert.Equal("Match", tree.ClassName);
        Assert.Equal(5, tree.Properties.Count);
        Assert.Equal("string", tree.Properties[0].Type.ToCSharp());
        Assert.Equal(0, tree.Properties[0].Mode);
        Assert.Equal("int", tree.Properties[2].Type.ToCSharp());
        Assert.Equal("DateTime", tree.Properties[3].Type.ToCSharp());
        Assert.Equal(1, tree.Properties[3].Mode);
        Assert.Equal(2, tree.Properties[4].Mode);
    }

    [Fact]
    public void Parse_ExplicitNamespace_AndUsings()
    {
        var parser = new TinyParser();
        var tree = parser.Parse("n:MyCompany.Domain\nu:System.Collections.Generic\nu:MyCompany.Contracts\npsc Match => Result:MatchResult");

        Assert.True(tree.IsValid);
        Assert.Equal("MyCompany.Domain", tree.Namespace);
        Assert.Equal(new[] { "System.Collections.Generic", "MyCompany.Contracts" }, tree.Usings);
        Assert.Equal("MatchResult", tree.Properties[0].Type.ToCSharp());
    }

    [Fact]
    public void Generate_ProducesHeaderNamespaceAndProperties()
    {
        var tree = new TinySyntaxTree
        {
            SourceFilePath = "/tmp/Match.tcs",
            Namespace = "Tiny.Sample",
            ClassName = "Match",
            Properties =
            {
                new TinyProperty("Id", "string", 0),
                new TinyProperty("Number", "int", 1),
                new TinyProperty("Code", "int", 2)
            }
        };

        var generator = new CSharpGenerator();
        var output = generator.Generate(tree);

        Assert.Contains("// <auto-generated />", output);
        Assert.Contains("// This file is generated from Match.tcs.", output);
        Assert.Contains("namespace Tiny.Sample;", output);
        Assert.Contains("public sealed class Match", output);
        Assert.Contains("public string Id { get; set; } = string.Empty;", output);
        Assert.Contains("public int Number { get; init; }", output);
        Assert.Contains("public int Code { get; private set; }", output);
    }

    [Fact]
    public void Parse_CompositionalTypes_ExpandsAliasesRecursively()
    {
        var parser = new TinyParser();
        var tree = parser.Parse(
            "psc Types => Maybe:s?,Ids:g[],Names:List<s>,Map:Dictionary<s,List<i>>,Work:Task<Result>|1");

        Assert.True(tree.IsValid);
        Assert.Equal("string?", tree.Properties[0].Type.ToCSharp());
        Assert.Equal("Guid[]", tree.Properties[1].Type.ToCSharp());
        Assert.Equal("List<string>", tree.Properties[2].Type.ToCSharp());
        Assert.Equal("Dictionary<string,List<int>>", tree.Properties[3].Type.ToCSharp());
        Assert.Equal("Task<Result>", tree.Properties[4].Type.ToCSharp());

        var output = new CSharpGenerator().Generate(tree);
        Assert.Contains("using System;", output);
        Assert.Contains("public string? Maybe { get; set; }", output);
        Assert.Contains("public Guid[] Ids { get; set; }", output);
        Assert.Contains("public Dictionary<string,List<int>> Map { get; set; }", output);
        Assert.DoesNotContain("Maybe { get; set; } = string.Empty;", output);
    }

    [Fact]
    public void Parse_InvalidType_ReportsStableCodeAndLocation()
    {
        var parser = new TinyParser();
        var tree = parser.Parse(
            "n:Example\npsc User => Name,List:List<s",
            "User.tcs");

        Assert.False(tree.IsValid);
        var diagnostic = Assert.Single(tree.Diagnostics);
        Assert.Equal("TCS1008", diagnostic.Code);
        Assert.Equal("User.tcs", diagnostic.FilePath);
        Assert.Equal(2, diagnostic.Line);
        Assert.True(diagnostic.Column > 1);
    }

    [Fact]
    public async Task CompileAsync_ResolvesTypeFromAnotherTinyFile_AndAddsUsing()
    {
        var root = Path.Combine(
            Path.GetTempPath(),
            "tinycs-resolution-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Path.Combine(root, "Contracts"));
        Directory.CreateDirectory(Path.Combine(root, "Models"));

        try
        {
            var projectPath = Path.Combine(root, "Example.csproj");
            await File.WriteAllTextAsync(
                projectPath,
                "<Project><PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Example</RootNamespace></PropertyGroup></Project>");

            await File.WriteAllTextAsync(
                Path.Combine(root, "Contracts", "Team.tcs"),
                "pc Team => Id");
            await File.WriteAllTextAsync(
                Path.Combine(root, "Models", "Match.tcs"),
                "psc Match => HomeTeam:Team");

            var result = await new TinyProjectCompiler().CompileAsync(projectPath);

            Assert.True(result.Success);
            Assert.DoesNotContain(
                result.Diagnostics,
                diagnostic => diagnostic.Code == "TCS2002");

            var output = await File.ReadAllTextAsync(
                Path.Combine(root, "Models", "Match.cs"));
            Assert.Contains("using Example.Contracts;", output);
            Assert.Contains("public Team HomeTeam { get; set; }", output);
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }
    }

    [Fact]
    public async Task CompileAsync_ResolvesTypeFromHandwrittenCSharp()
    {
        var root = Path.Combine(
            Path.GetTempPath(),
            "tinycs-csharp-resolution-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Path.Combine(root, "Contracts"));
        Directory.CreateDirectory(Path.Combine(root, "Models"));

        try
        {
            var projectPath = Path.Combine(root, "Example.csproj");
            await File.WriteAllTextAsync(
                projectPath,
                "<Project><PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Example</RootNamespace></PropertyGroup></Project>");
            await File.WriteAllTextAsync(
                Path.Combine(root, "Contracts", "HandwrittenResolutionContract.cs"),
                "namespace Example.Contracts; public class HandwrittenResolutionContract { }");
            await File.WriteAllTextAsync(
                Path.Combine(root, "Models", "Model.tcs"),
                "pc Model => Value:HandwrittenResolutionContract");

            var result = await new TinyProjectCompiler().CompileAsync(projectPath);

            Assert.True(result.Success);
            var output = await File.ReadAllTextAsync(
                Path.Combine(root, "Models", "Model.cs"));
            Assert.Contains("using Example.Contracts;", output);
            Assert.Contains(
                "public HandwrittenResolutionContract Value { get; set; }",
                output);
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }
    }

    [Fact]
    public async Task CompileAsync_UnresolvedType_WarnsAndEmitsNameUnchanged()
    {
        var root = Path.Combine(
            Path.GetTempPath(),
            "tinycs-unresolved-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);

        try
        {
            var projectPath = Path.Combine(root, "Example.csproj");
            await File.WriteAllTextAsync(
                projectPath,
                "<Project><PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Example</RootNamespace></PropertyGroup></Project>");
            await File.WriteAllTextAsync(
                Path.Combine(root, "Model.tcs"),
                "pc Model => Value:MissingType");

            var result = await new TinyProjectCompiler().CompileAsync(projectPath);

            Assert.True(result.Success);
            var diagnostic = Assert.Single(
                result.Diagnostics,
                diagnostic => diagnostic.Code == "TCS2002");
            Assert.Equal(TinyDiagnosticSeverity.Warning, diagnostic.Severity);
            Assert.True(diagnostic.Line > 0);
            Assert.True(diagnostic.Column > 0);

            var output = await File.ReadAllTextAsync(
                Path.Combine(root, "Model.cs"));
            Assert.Contains("public MissingType Value { get; set; }", output);
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }
    }

    [Fact]
    public async Task CompileAsync_AmbiguousType_WarnsAndQualifiesDeterministicSelection()
    {
        var root = Path.Combine(
            Path.GetTempPath(),
            "tinycs-ambiguous-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Path.Combine(root, "A"));
        Directory.CreateDirectory(Path.Combine(root, "B"));
        Directory.CreateDirectory(Path.Combine(root, "Models"));

        try
        {
            var projectPath = Path.Combine(root, "Example.csproj");
            await File.WriteAllTextAsync(
                projectPath,
                "<Project><PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Example</RootNamespace></PropertyGroup></Project>");
            await File.WriteAllTextAsync(
                Path.Combine(root, "A", "Team.tcs"),
                "pc Team => Id");
            await File.WriteAllTextAsync(
                Path.Combine(root, "B", "Team.tcs"),
                "pc Team => Id");
            await File.WriteAllTextAsync(
                Path.Combine(root, "Models", "Match.tcs"),
                "pc Match => HomeTeam:Team");

            var result = await new TinyProjectCompiler().CompileAsync(projectPath);

            Assert.True(result.Success);
            var diagnostic = Assert.Single(
                result.Diagnostics,
                diagnostic => diagnostic.Code == "TCS2001");
            Assert.Contains("Example.A.Team", diagnostic.Message);
            Assert.Contains("Example.B.Team", diagnostic.Message);

            var output = await File.ReadAllTextAsync(
                Path.Combine(root, "Models", "Match.cs"));
            Assert.Contains(
                "public Example.A.Team HomeTeam { get; set; }",
                output);
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }
    }

    [Fact]
    public async Task CompileAsync_OverwritesSiblingCs_AndInfersNamespace()
    {
        var root = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);

        try
        {
            var projectPath = Path.Combine(root, "MyCompany.App.csproj");
            await File.WriteAllTextAsync(projectPath, "<Project><PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Tiny.Sample</RootNamespace></PropertyGroup></Project>");

            var folder = Path.Combine(root, "Domain", "Matches");
            Directory.CreateDirectory(folder);

            var tcsPath = Path.Combine(folder, "Match.tcs");
            var csPath = Path.Combine(folder, "Match.cs");

            await File.WriteAllTextAsync(tcsPath, "psc Match => Id,Name");
            await File.WriteAllTextAsync(csPath, "// manual file\nclass Old { }");

            var compiler = new TinyProjectCompiler();
            var result = await compiler.CompileAsync(projectPath);

            Assert.True(result.Success);
            var output = await File.ReadAllTextAsync(csPath);
            Assert.Contains("// <auto-generated />", output);
            Assert.Contains("namespace Tiny.Sample.Domain.Matches;", output);
            Assert.DoesNotContain("manual file", output);
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }
    }
}
