using TinyCSharp.Compiler.Diagnostics;
using TinyCSharp.Compiler.Generation;

namespace TinyCSharp.Compiler.Decompilation;

public sealed class CSharpProjectDecompiler
{
    public async Task<CSharpProjectDecompilationResult> DecompileAsync(
        string projectPath,
        string outputDirectory,
        CancellationToken cancellationToken = default)
    {
        if (!File.Exists(projectPath))
        {
            return Failure(
                projectPath,
                "Project file not found.");
        }

        var projectDirectory = Path.GetDirectoryName(Path.GetFullPath(projectPath));
        if (string.IsNullOrWhiteSpace(projectDirectory))
        {
            return Failure(
                projectPath,
                "Could not determine the project directory.");
        }

        var sourceFiles = Directory
            .EnumerateFiles(projectDirectory, "*.cs", SearchOption.AllDirectories)
            .Where(path => !IsExcludedPath(projectDirectory, path))
            .Where(path => !File.Exists(Path.ChangeExtension(path, ".tcs")))
            .OrderBy(path => path, StringComparer.Ordinal)
            .ToArray();

        var sourceDocuments = new List<CSharpSourceDocument>();

        foreach (var sourceFile in sourceFiles)
        {
            var source = await File.ReadAllTextAsync(sourceFile, cancellationToken);

            if (IsGeneratedSource(source))
            {
                continue;
            }

            sourceDocuments.Add(new CSharpSourceDocument(
                Path.GetFullPath(sourceFile),
                source));
        }

        if (sourceDocuments.Count == 0)
        {
            return new CSharpProjectDecompilationResult(
                true,
                Array.Empty<CSharpProjectDecompiledFile>(),
                Array.Empty<CSharpProjectDecompilationDiagnostic>());
        }

        var semanticCompilation = CSharpSemanticCompilation.Create(sourceDocuments);
        var decompiler = new CSharpDecompiler();
        var formatter = new TinyFormatter();
        var files = new List<CSharpProjectDecompiledFile>();
        var diagnostics = new List<CSharpProjectDecompilationDiagnostic>();

        foreach (var sourceDocument in sourceDocuments)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = decompiler.Decompile(
                semanticCompilation,
                sourceDocument.FilePath);

            if (!result.Success || result.Document is null)
            {
                diagnostics.AddRange(result.Diagnostics.Select(
                    diagnostic => new CSharpProjectDecompilationDiagnostic(
                        sourceDocument.FilePath,
                        diagnostic.Code,
                        diagnostic.Message,
                        diagnostic.Line,
                        diagnostic.Column)));
                continue;
            }

            var relativePath = Path.GetRelativePath(
                projectDirectory,
                sourceDocument.FilePath);
            var relativeTinyPath = Path.ChangeExtension(relativePath, ".tcs");
            var outputPath = Path.GetFullPath(
                Path.Combine(outputDirectory, relativeTinyPath));

            Directory.CreateDirectory(
                Path.GetDirectoryName(outputPath) ?? outputDirectory);

            await File.WriteAllTextAsync(
                outputPath,
                formatter.Format(result.Document),
                cancellationToken);

            files.Add(new CSharpProjectDecompiledFile(
                sourceDocument.FilePath,
                outputPath));
        }

        return new CSharpProjectDecompilationResult(
            diagnostics.Count == 0,
            files,
            diagnostics);
    }

    private static bool IsExcludedPath(
        string projectDirectory,
        string filePath)
    {
        var relative = Path.GetRelativePath(projectDirectory, filePath);
        var segments = relative.Split(
            new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar },
            StringSplitOptions.RemoveEmptyEntries);

        if (segments.Any(segment =>
                string.Equals(segment, "bin", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(segment, "obj", StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        var fileName = Path.GetFileName(filePath);

        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsGeneratedSource(string source)
    {
        var prefixLength = Math.Min(source.Length, 512);
        return source.AsSpan(0, prefixLength)
            .Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
    }

    private static CSharpProjectDecompilationResult Failure(
        string filePath,
        string message)
    {
        return new CSharpProjectDecompilationResult(
            false,
            Array.Empty<CSharpProjectDecompiledFile>(),
            new[]
            {
                new CSharpProjectDecompilationDiagnostic(
                    filePath,
                    TinyDiagnosticCodes.UnsupportedCSharpConstruct,
                    message,
                    1,
                    1)
            });
    }
}

public sealed record CSharpProjectDecompiledFile(
    string SourcePath,
    string OutputPath);

public sealed record CSharpProjectDecompilationDiagnostic(
    string FilePath,
    string Code,
    string Message,
    int Line,
    int Column);

public sealed record CSharpProjectDecompilationResult(
    bool Success,
    IReadOnlyList<CSharpProjectDecompiledFile> Files,
    IReadOnlyList<CSharpProjectDecompilationDiagnostic> Diagnostics);
